### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by josevalim** [elixir-makeup/makeup_html#6]
@javiergarea, can you please do a new release? Or feel free to add me as an owner to hex.pm, and I can do it. :)

**Comment by javiergarea** [comment]
Sure! `makeup_html v0.1.1` has been published on hex.pm. Regarding the ownership, I can't make the task succeed:
```sh
❯ mix hex.owner add makeup_html jose.valim@dashbit.co
Local password:
Adding owner jose.valim@dashbit.co with ownership level full to makeup_html
Adding owner failed
Page not found
```

**Comment by josevalim** [comment]
@javiergarea please use `@gmail.com` :)

**Comment by javiergarea** [comment]
Done! :shipit:

**Comment by javiergarea** [comment]
@josevalim should we close this?
